config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'missing', to: 'pages#missing'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	include Placeholder

	validates_presence_of :title, :body, :main_image, :thumb_image

	has_many :technologies
	accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

	def self.angular
		where(subtitle: "Angular")
	end

	scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails") }

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '400', width: '600')
		self.thumb_image ||= Placeholder.image_generator(height: '200', width: '350')
	end

	def self.by_position
		order("position ASC")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio, only: [:edit, :update, :show, :destroy]
	layout "portfolio"

	access all: [:show, :index, :angular], user: { except: [:destroy, :new, :create, :update, :edit] }, site_admin: :all

	def index
		@portfolios = Portfolio.by_position
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def show
	end

	def new
		@portfolio_item = Portfolio.new
		3.times { @portfolio_item.technologies.build }
	end

	def create
		@portfolio_item = Portfolio.new(portfolio_params)

		respond_to do |format|
			if @portfolio_item.save
				format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live"}
			else
				format.html { render :new }
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @portfolio_item.update(portfolio_params)
				format.html { redirect_to portfolios_path, notice: "The portfolio was successfully updated."}
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@portfolio_item.destroy
		respond_to do |format|
			format.html { redirect_to portfolios_url, notice: "Record was removed." }
		end
	end

	private

	def set_portfolio
		@portfolio_item = Portfolio.find(params[:id])
	end

	def portfolio_params
		params.require(:portfolio).permit(
			:title,
			:subtitle, 
			:body,
			technologies_attributes: [:name]
		)
	end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= form.label :title, style: "display: block", class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :subtitle, style: "display: block", class: "form-label" %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="field">
        <%= form.label :body, style: "display: block", class: "form-label" %>
        <%= form.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |tech| %>
        <div class="field">
          <%= tech.label :name, class: "form-label" %>
          <%= tech.text_field :name, class: "form-control" %>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.submit "Save Portfolio Item", class: "btn btn-primary col-12" %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col">
	<div class="card shadow-sm">
		<%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
		<div class="card-body">
			<p class="card-text">
				<span><%= link_to portfolio.title, portfolio_show_path(portfolio) %></span>
				<%= portfolio.subtitle %>
			</p>
		</div>
	</div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<p style="color: green"><%= notice %></p>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |item| %>
 <p><%= link_to item.title, portfolio_show_path(item) %></p>
 <p><%= item.subtitle %></p>
 <p><%= item.body %></p>
 <%= image_tag(item.thumb_image, style: "width: 200px") unless item.thumb_image.nil? %>
 <%= link_to "Edit", edit_portfolio_path(item) if logged_in?(:site_admin) %>
 <%= link_to "Delete", item, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
	<h1>Edit This Porfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 sortable">
				<%= render @portfolios %>
		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
	<h1>Create a New Porfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag @portfolio_item.main_image %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>

			<p>
				<%= link_to "Edit", edit_portfolio_path(@portfolio_item) if logged_in?(:site_admin) %> |
				<%= link_to "Delete", @portfolio_item, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } if logged_in?(:site_admin) %>
			</p>

			<em><%= @portfolio_item.subtitle %></em>

			<p><%= @portfolio_item.body %></p>

			<hr>

			<h2>Technologies Used:</h2>

			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %><p>
			<% end %>
		</div>
	</div>
</div>